# Generated by Django 2.2.12 on 2020-07-01 10:44

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oeuvre", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oeuvre",
            name="type_oeuvre",
        ),
        migrations.DeleteModel(
            name="Presentation",
        ),
        migrations.AlterField(
            model_name="poesie",
            name="poeme",
            field=tinymce.models.HTMLField(),
        ),
        migrations.DeleteModel(
            name="Oeuvre",
        ),
        migrations.DeleteModel(
            name="TypeOeuvre",
        ),
    ]
